/**
 * THIS FILE IS GENERATED BY jsonrpcstub, DO NOT CHANGE IT!!!!!
 */

#ifndef _TEST_CLIENT_H_
#define _TEST_CLIENT_H_

#include <jsonrpc/rpc.h>
#include "gazebotestclient.h"

namespace gztest
{
  class TestClient
  {
    public:
      TestClient(std::string address);
      ~TestClient();
      bool onObject(const std::string& object, const std::string& surface);
    private:
      GazeboTestClient* client;
  };
}
#endif 
